FROM golang:1.19 AS builder

WORKDIR /src

# Add source code
COPY . .

# Download dependencies
RUN go mod download


RUN CGO_ENABLED=0 go build -o srv ./server/server.go

FROM alpine AS production
RUN apk --no-cache add ca-certificates bash make

WORKDIR /app
# Retrieve the binary from the previous stage
COPY --from=builder /src/srv .

CMD ["./srv"]